### ISSUE TITLE
Incorrectly marking valid code as invalid

### ISSUE THREAD

**Issue by ayvacs** [UnderMyWheel/vscode-luau#14]
I've seen it mark this stuff as wrong when it's actually valid Luau code:

- Type checking
<img width="648" alt="image" src="https://user-images.githubusercontent.com/74518502/162638001-03aab990-9f2e-4cb8-9763-863a3403c483.png">

- The `+=` & `-=` operators
<img width="328" alt="image" src="https://user-images.githubusercontent.com/74518502/162638058-4b2b3345-6d7d-4e0f-9f6a-259e5efb2800.png">

That code is all valid Luau (runs fine in-game and in studio)

**Comment by UnderMyWheel** [comment]
The Luau extension only provides syntax highlighting and snippets. The type check errors are potentially the result of another extension you have installed.
