### ISSUE TITLE
Add a macro which automatically applies end two lines down when "then", "function" & "do".

### ISSUE THREAD

**Issue by Ewanophobia** [UnderMyWheel/vscode-luau#3]
It's only a simple macro and will help a lot with workflow and efficiency.

**Comment by UnderMyWheel** [comment]
I will look into adding this into the next update.

**Comment by UnderMyWheel** [comment]
I believe this feature is better suited for another extension such as Roblox LSP. The goal of the Luau extension is to only provide syntax highlighting and snippet support.
