### ISSUE TITLE
Incorrect partial word syntax highlighting

### ISSUE THREAD

**Issue by evaera** [UnderMyWheel/vscode-luau#4]
![image](https://user-images.githubusercontent.com/2489210/87704956-28e8e080-c76b-11ea-931b-49bc5ee9b412.png)

`game` gets highlighted as a key word here, but it's part of a parameter identifier!

**Comment by UnderMyWheel** [comment]
Going to look into a fix in the new update so it does not highlight keywords used in parameter, function, or variable names.

**Comment by UnderMyWheel** [comment]
This has been fixed in version 1.0.3 @evaera
