### ISSUE TITLE
Incompatible with the Selene VSCode extension

### ISSUE THREAD

**Issue by filiptibell** [UnderMyWheel/vscode-luau#5]
This extension uses a special language id (luau) in the package.json contributions instead of the normal "lua" language id that other extensions use, such as the VSCode extension for Selene. This make the extension incompatible with Selene for linting.

**Comment by UnderMyWheel** [comment]
Will look into changing the language id this week. My original intent with this was to allow developers to easily switch between Lua or Luau without having to disable the extension everytime.

**Comment by UnderMyWheel** [comment]
The incompatibilities have been fixed in version 1.0.2 @filiptibell
