### ISSUE TITLE
Numbers with underscore separators directly followed by a comma/semicolon don't get highlighted

### ISSUE THREAD

**Issue by filiptibell** [UnderMyWheel/vscode-luau#7]
These numbers don't get highlighted when they should be:

![m5GHAnM](https://user-images.githubusercontent.com/9497781/88720253-d91ff700-d124-11ea-8427-3c58e48215ce.png)

However, add a space and it's fine:

![XzurCm1](https://user-images.githubusercontent.com/9497781/88720258-db825100-d124-11ea-9a19-7ad4b026e40e.png)

**Comment by UnderMyWheel** [comment]
This has been fixed in version 1.0.3 @filiptibell
