### ISSUE TITLE
Multiple spaces after each other break syntax highlighting

### ISSUE THREAD

**Issue by filiptibell** [UnderMyWheel/vscode-luau#9]
![m0DcO6E](https://user-images.githubusercontent.com/9497781/89123475-e09e2200-d4cf-11ea-9846-d05e5b2bc75d.png)

Several spaces following each other (any type, newline, tabs, normal space) will break syntax highligting as of version 1.0.3

**Comment by UnderMyWheel** [comment]
This has been fixed in version 1.0.4 @filiptibell
